networks:
  local-net:
    name: local-net
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/24

secrets:
  postgres_password:
    file: ./secrets/pw_postgres

services:

  db:
    build:
      network: host
      context: .
      dockerfile: Dockerfile.postgres
    image: local/postgres:15.2
    container_name: db
    networks:
      local-net:
        aliases:
          - db
    ports:
      - "5432:5432"
    secrets:
      - postgres_password
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: db

  flywaydb:
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    image: docker.schipplock.de/flywaydb:9.16.1
    container_name: flywaydb
    networks:
      local-net:
        aliases:
          - flywaydb
    secrets:
      - postgres_password
    environment:
      FLYWAY_POSTGRES_HOST: db
      FLYWAY_POSTGRES_PORT: 5432
      FLYWAY_POSTGRES_USER: db
      FLYWAY_POSTGRES_DB: db
      FLYWAY_POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      FLYWAY_CONNECT_RETRIES: 5
      FLYWAY_SCHEMAS: "public"
      FLYWAY_TABLE: "schema_history"
      FLYWAY_LOCATIONS: "filesystem:/migrations"
      FLYWAY_ENCODING: "UTF-8"
    volumes:
      - ./sql-migrations:/migrations:ro
    depends_on:
      - db